### ISSUE TITLE
How can we build it?

### ISSUE THREAD

**Issue by mvaranda** [small-teton/MpegTsAnalyzer#4]
I am not a go developer. 
Once I tried "go get ." or "go install" it tries  to fetch modules from wrong paths. All my attempts to export GOPATH and GOROOT had failed. Thanks in advance.

**Comment by small-teton** [comment]
Hi, @mvaranda 

MpegTsAnalyzer was written in a very old go version.
It was also not clear which go version it was written in. This made it difficult for others to build it.

Therefore, I have made it possible to build it with 1.21.4, which is currently the latest go version.

I also made it so that gorelease automatically builds binaries for each platform.
If you like, you can download the binaries from the following page.
https://github.com/small-teton/MpegTsAnalyzer/releases

**Comment by mvaranda** [comment]
Hi, thanks for your attention. I had solved the problem I had with my streams. Therefore, no need at the moment to investigate them with this tool. However, it is great to have this TS analyzer working. I will check it out in the future once I have a need for it.
